// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TrackGroup,
  TrackKind,
} from "./types";

export default {
  projectId: __t.string(),
  trackId: __t.string(),
  sceneId: __t.string(),
  get group() {
    return TrackGroup;
  },
  get kind() {
    return TrackKind;
  },
  name: __t.string(),
  position: __t.u32(),
};
