// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AssetStorage,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  projectId: __t.string().name("project_id"),
  name: __t.string(),
  get storage() {
    return AssetStorage;
  },
  location: __t.string(),
  mimeType: __t.string().name("mime_type"),
  byteSize: __t.option(__t.u64()).name("byte_size"),
  width: __t.option(__t.u32()),
  height: __t.option(__t.u32()),
  duration: __t.option(__t.i64()),
  createdAt: __t.timestamp().name("created_at"),
});
