// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ClipKind,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  projectId: __t.string().name("project_id"),
  trackId: __t.string().name("track_id"),
  get kind() {
    return ClipKind;
  },
  name: __t.string(),
  startTime: __t.i64().name("start_time"),
  duration: __t.i64(),
  trimStart: __t.i64().name("trim_start"),
  trimEnd: __t.i64().name("trim_end"),
  sourceDuration: __t.option(__t.i64()).name("source_duration"),
  mediaId: __t.option(__t.string()).name("media_id"),
  rate: __t.f64(),
  volumeDb: __t.f32().name("volume_db"),
  muted: __t.bool(),
  hidden: __t.bool(),
  data: __t.string(),
  revision: __t.u64(),
  updatedAt: __t.timestamp().name("updated_at"),
  updatedBy: __t.identity().name("updated_by"),
  origin: __t.option(__t.connectionId()),
});
