// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  clipId: __t.string().name("clip_id"),
  projectId: __t.string().name("project_id"),
  effectType: __t.string().name("effect_type"),
  position: __t.u32(),
  enabled: __t.bool(),
  params: __t.string(),
  revision: __t.u64(),
});
