// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ActorKind,
  MemberRole,
} from "./types";


export default __t.row({
  connectionId: __t.connectionId().primaryKey().name("connection_id"),
  projectId: __t.string().name("project_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  color: __t.string(),
  get kind() {
    return ActorKind;
  },
  get role() {
    return MemberRole;
  },
  canWrite: __t.bool().name("can_write"),
  atCapacity: __t.bool().name("at_capacity"),
  lastSeen: __t.timestamp().name("last_seen"),
});
