// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EditOp,
  ActorKind,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  projectId: __t.string().name("project_id"),
  revision: __t.u64(),
  get op() {
    return EditOp;
  },
  targetId: __t.string().name("target_id"),
  actor: __t.identity(),
  get actorKind() {
    return ActorKind.name("actor_kind");
  },
  origin: __t.option(__t.connectionId()),
  summary: __t.string(),
  payload: __t.string(),
  at: __t.timestamp(),
});
