// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddClipReducer from "./add_clip_reducer";
import AddEffectReducer from "./add_effect_reducer";
import AddSceneReducer from "./add_scene_reducer";
import AddTrackReducer from "./add_track_reducer";
import ClearPresenceReducer from "./clear_presence_reducer";
import CreateProjectReducer from "./create_project_reducer";
import CreateShareInviteReducer from "./create_share_invite_reducer";
import DeclareAgentReducer from "./declare_agent_reducer";
import DeleteClipReducer from "./delete_clip_reducer";
import DeleteProjectReducer from "./delete_project_reducer";
import DeleteTrackReducer from "./delete_track_reducer";
import JoinProjectReducer from "./join_project_reducer";
import LeaveSessionReducer from "./leave_session_reducer";
import MoveClipReducer from "./move_clip_reducer";
import PutAssetChunkReducer from "./put_asset_chunk_reducer";
import RefreshParticipantsReducer from "./refresh_participants_reducer";
import RegisterAssetReducer from "./register_asset_reducer";
import RemoveAssetReducer from "./remove_asset_reducer";
import RemoveEffectReducer from "./remove_effect_reducer";
import RemoveParticipantReducer from "./remove_participant_reducer";
import RenameProjectReducer from "./rename_project_reducer";
import ReorderEffectReducer from "./reorder_effect_reducer";
import ReorderTrackReducer from "./reorder_track_reducer";
import SendChatMessageReducer from "./send_chat_message_reducer";
import SetClipHiddenReducer from "./set_clip_hidden_reducer";
import SetClipMutedReducer from "./set_clip_muted_reducer";
import SetParticipantAccessReducer from "./set_participant_access_reducer";
import SetPlayheadReducer from "./set_playhead_reducer";
import SetProjectMetadataReducer from "./set_project_metadata_reducer";
import SetSelectionReducer from "./set_selection_reducer";
import SetTrackHiddenReducer from "./set_track_hidden_reducer";
import SetTrackMutedReducer from "./set_track_muted_reducer";
import SetUserProfileReducer from "./set_user_profile_reducer";
import SetVolumeReducer from "./set_volume_reducer";
import SplitClipReducer from "./split_clip_reducer";
import StartLiveSessionReducer from "./start_live_session_reducer";
import StopLiveSessionReducer from "./stop_live_session_reducer";
import ToggleEffectReducer from "./toggle_effect_reducer";
import TrimClipReducer from "./trim_clip_reducer";
import UpdateClipDataReducer from "./update_clip_data_reducer";
import UpdateEffectParamsReducer from "./update_effect_params_reducer";
import UpdatePresenceReducer from "./update_presence_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AssetRow from "./asset_table";
import AssetChunkRow from "./asset_chunk_table";
import ChatMessageRow from "./chat_message_table";
import ClipRow from "./clip_table";
import ClipEffectRow from "./clip_effect_table";
import CollaboratorRow from "./collaborator_table";
import EditHistoryRow from "./edit_history_table";
import LiveSessionRow from "./live_session_table";
import PresenceRow from "./presence_table";
import ProjectRow from "./project_table";
import ProjectMemberRow from "./project_member_table";
import ProjectMetadataRow from "./project_metadata_table";
import SceneRow from "./scene_table";
import ShareInviteRow from "./share_invite_table";
import TrackRow from "./track_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  asset: __table({
    name: 'asset',
    indexes: [
      { accessor: 'id', name: 'asset_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'asset_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'asset_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AssetRow),
  assetChunk: __table({
    name: 'asset_chunk',
    indexes: [
      { accessor: 'asset_id', name: 'asset_chunk_asset_id_idx_btree', algorithm: 'btree', columns: [
        'assetId',
      ] },
      { accessor: 'id', name: 'asset_chunk_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'asset_chunk_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'asset_chunk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AssetChunkRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'id', name: 'chat_message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'chat_message_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  clip: __table({
    name: 'clip',
    indexes: [
      { accessor: 'id', name: 'clip_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'clip_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
      { accessor: 'track_id', name: 'clip_track_id_idx_btree', algorithm: 'btree', columns: [
        'trackId',
      ] },
    ],
    constraints: [
      { name: 'clip_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClipRow),
  clipEffect: __table({
    name: 'clip_effect',
    indexes: [
      { accessor: 'clip_id', name: 'clip_effect_clip_id_idx_btree', algorithm: 'btree', columns: [
        'clipId',
      ] },
      { accessor: 'id', name: 'clip_effect_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'clip_effect_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'clip_effect_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClipEffectRow),
  collaborator: __table({
    name: 'collaborator',
    indexes: [
      { accessor: 'connection_id', name: 'collaborator_connection_id_idx_btree', algorithm: 'btree', columns: [
        'connectionId',
      ] },
      { accessor: 'project_id', name: 'collaborator_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'collaborator_connection_id_key', constraint: 'unique', columns: ['connectionId'] },
    ],
  }, CollaboratorRow),
  editHistory: __table({
    name: 'edit_history',
    indexes: [
      { accessor: 'id', name: 'edit_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'edit_history_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'edit_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EditHistoryRow),
  liveSession: __table({
    name: 'live_session',
    indexes: [
      { accessor: 'project_id', name: 'live_session_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'live_session_project_id_key', constraint: 'unique', columns: ['projectId'] },
    ],
  }, LiveSessionRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'connection_id', name: 'presence_connection_id_idx_btree', algorithm: 'btree', columns: [
        'connectionId',
      ] },
      { accessor: 'project_id', name: 'presence_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'presence_connection_id_key', constraint: 'unique', columns: ['connectionId'] },
    ],
  }, PresenceRow),
  project: __table({
    name: 'project',
    indexes: [
      { accessor: 'id', name: 'project_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'project_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectRow),
  projectMember: __table({
    name: 'project_member',
    indexes: [
      { accessor: 'id', name: 'project_member_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_project_identity', name: 'project_member_project_id_identity_idx_btree', algorithm: 'btree', columns: [
        'projectId',
        'identity',
      ] },
      { accessor: 'project_id', name: 'project_member_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'project_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProjectMemberRow),
  projectMetadata: __table({
    name: 'project_metadata',
    indexes: [
      { accessor: 'project_id', name: 'project_metadata_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'project_metadata_project_id_key', constraint: 'unique', columns: ['projectId'] },
    ],
  }, ProjectMetadataRow),
  scene: __table({
    name: 'scene',
    indexes: [
      { accessor: 'id', name: 'scene_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'scene_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
    ],
    constraints: [
      { name: 'scene_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SceneRow),
  shareInvite: __table({
    name: 'share_invite',
    indexes: [
      { accessor: 'project_id', name: 'share_invite_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
      { accessor: 'token', name: 'share_invite_token_idx_btree', algorithm: 'btree', columns: [
        'token',
      ] },
    ],
    constraints: [
      { name: 'share_invite_token_key', constraint: 'unique', columns: ['token'] },
    ],
  }, ShareInviteRow),
  track: __table({
    name: 'track',
    indexes: [
      { accessor: 'id', name: 'track_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'project_id', name: 'track_project_id_idx_btree', algorithm: 'btree', columns: [
        'projectId',
      ] },
      { accessor: 'scene_id', name: 'track_scene_id_idx_btree', algorithm: 'btree', columns: [
        'sceneId',
      ] },
    ],
    constraints: [
      { name: 'track_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TrackRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_clip", AddClipReducer),
  __reducerSchema("add_effect", AddEffectReducer),
  __reducerSchema("add_scene", AddSceneReducer),
  __reducerSchema("add_track", AddTrackReducer),
  __reducerSchema("clear_presence", ClearPresenceReducer),
  __reducerSchema("create_project", CreateProjectReducer),
  __reducerSchema("create_share_invite", CreateShareInviteReducer),
  __reducerSchema("declare_agent", DeclareAgentReducer),
  __reducerSchema("delete_clip", DeleteClipReducer),
  __reducerSchema("delete_project", DeleteProjectReducer),
  __reducerSchema("delete_track", DeleteTrackReducer),
  __reducerSchema("join_project", JoinProjectReducer),
  __reducerSchema("leave_session", LeaveSessionReducer),
  __reducerSchema("move_clip", MoveClipReducer),
  __reducerSchema("put_asset_chunk", PutAssetChunkReducer),
  __reducerSchema("refresh_participants", RefreshParticipantsReducer),
  __reducerSchema("register_asset", RegisterAssetReducer),
  __reducerSchema("remove_asset", RemoveAssetReducer),
  __reducerSchema("remove_effect", RemoveEffectReducer),
  __reducerSchema("remove_participant", RemoveParticipantReducer),
  __reducerSchema("rename_project", RenameProjectReducer),
  __reducerSchema("reorder_effect", ReorderEffectReducer),
  __reducerSchema("reorder_track", ReorderTrackReducer),
  __reducerSchema("send_chat_message", SendChatMessageReducer),
  __reducerSchema("set_clip_hidden", SetClipHiddenReducer),
  __reducerSchema("set_clip_muted", SetClipMutedReducer),
  __reducerSchema("set_participant_access", SetParticipantAccessReducer),
  __reducerSchema("set_playhead", SetPlayheadReducer),
  __reducerSchema("set_project_metadata", SetProjectMetadataReducer),
  __reducerSchema("set_selection", SetSelectionReducer),
  __reducerSchema("set_track_hidden", SetTrackHiddenReducer),
  __reducerSchema("set_track_muted", SetTrackMutedReducer),
  __reducerSchema("set_user_profile", SetUserProfileReducer),
  __reducerSchema("set_volume", SetVolumeReducer),
  __reducerSchema("split_clip", SplitClipReducer),
  __reducerSchema("start_live_session", StartLiveSessionReducer),
  __reducerSchema("stop_live_session", StopLiveSessionReducer),
  __reducerSchema("toggle_effect", ToggleEffectReducer),
  __reducerSchema("trim_clip", TrimClipReducer),
  __reducerSchema("update_clip_data", UpdateClipDataReducer),
  __reducerSchema("update_effect_params", UpdateEffectParamsReducer),
  __reducerSchema("update_presence", UpdatePresenceReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

type __SchemaWithTableAccessorAliases = Omit<typeof tablesSchema.schemaType, "tables"> & {
  tables: typeof tablesSchema.schemaType.tables & {
    /** @deprecated Use `assetChunk` instead. This alias will be removed in the next major version. */
    readonly "asset_chunk": Omit<typeof tablesSchema.schemaType.tables["assetChunk"], "accessorName"> & { readonly accessorName: "asset_chunk" };
    /** @deprecated Use `chatMessage` instead. This alias will be removed in the next major version. */
    readonly "chat_message": Omit<typeof tablesSchema.schemaType.tables["chatMessage"], "accessorName"> & { readonly accessorName: "chat_message" };
    /** @deprecated Use `clipEffect` instead. This alias will be removed in the next major version. */
    readonly "clip_effect": Omit<typeof tablesSchema.schemaType.tables["clipEffect"], "accessorName"> & { readonly accessorName: "clip_effect" };
    /** @deprecated Use `editHistory` instead. This alias will be removed in the next major version. */
    readonly "edit_history": Omit<typeof tablesSchema.schemaType.tables["editHistory"], "accessorName"> & { readonly accessorName: "edit_history" };
    /** @deprecated Use `liveSession` instead. This alias will be removed in the next major version. */
    readonly "live_session": Omit<typeof tablesSchema.schemaType.tables["liveSession"], "accessorName"> & { readonly accessorName: "live_session" };
    /** @deprecated Use `projectMember` instead. This alias will be removed in the next major version. */
    readonly "project_member": Omit<typeof tablesSchema.schemaType.tables["projectMember"], "accessorName"> & { readonly accessorName: "project_member" };
    /** @deprecated Use `projectMetadata` instead. This alias will be removed in the next major version. */
    readonly "project_metadata": Omit<typeof tablesSchema.schemaType.tables["projectMetadata"], "accessorName"> & { readonly accessorName: "project_metadata" };
    /** @deprecated Use `shareInvite` instead. This alias will be removed in the next major version. */
    readonly "share_invite": Omit<typeof tablesSchema.schemaType.tables["shareInvite"], "accessorName"> & { readonly accessorName: "share_invite" };
  };
};

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables as __SchemaWithTableAccessorAliases["tables"],
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  __SchemaWithTableAccessorAliases,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

const tableAccessorAliases = {
  "asset_chunk": "assetChunk",
  "chat_message": "chatMessage",
  "clip_effect": "clipEffect",
  "edit_history": "editHistory",
  "live_session": "liveSession",
  "project_member": "projectMember",
  "project_metadata": "projectMetadata",
  "share_invite": "shareInvite",
} as const;

function __withTableAccessorAliases<T extends object>(target: T, freeze = false): T {
  const out = Object.create(Object.getPrototypeOf(target)) as T & Record<string, unknown>;
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor],
    });
  }
  return freeze ? Object.freeze(out) : out;
}

type __DbViewBase = __DbConnectionImpl<typeof REMOTE_MODULE>["db"];
export type DbView = __DbViewBase & {
  /** @deprecated Use `assetChunk` instead. This alias will be removed in the next major version. */
  readonly "asset_chunk": __DbViewBase["assetChunk"];
  /** @deprecated Use `chatMessage` instead. This alias will be removed in the next major version. */
  readonly "chat_message": __DbViewBase["chatMessage"];
  /** @deprecated Use `clipEffect` instead. This alias will be removed in the next major version. */
  readonly "clip_effect": __DbViewBase["clipEffect"];
  /** @deprecated Use `editHistory` instead. This alias will be removed in the next major version. */
  readonly "edit_history": __DbViewBase["editHistory"];
  /** @deprecated Use `liveSession` instead. This alias will be removed in the next major version. */
  readonly "live_session": __DbViewBase["liveSession"];
  /** @deprecated Use `projectMember` instead. This alias will be removed in the next major version. */
  readonly "project_member": __DbViewBase["projectMember"];
  /** @deprecated Use `projectMetadata` instead. This alias will be removed in the next major version. */
  readonly "project_metadata": __DbViewBase["projectMetadata"];
  /** @deprecated Use `shareInvite` instead. This alias will be removed in the next major version. */
  readonly "share_invite": __DbViewBase["shareInvite"];
};

type __TablesBase = __QueryBuilder<typeof tablesSchema.schemaType>;
export type Tables = __TablesBase & {
  /** @deprecated Use `assetChunk` instead. This alias will be removed in the next major version. */
  readonly "asset_chunk": __TablesBase["assetChunk"];
  /** @deprecated Use `chatMessage` instead. This alias will be removed in the next major version. */
  readonly "chat_message": __TablesBase["chatMessage"];
  /** @deprecated Use `clipEffect` instead. This alias will be removed in the next major version. */
  readonly "clip_effect": __TablesBase["clipEffect"];
  /** @deprecated Use `editHistory` instead. This alias will be removed in the next major version. */
  readonly "edit_history": __TablesBase["editHistory"];
  /** @deprecated Use `liveSession` instead. This alias will be removed in the next major version. */
  readonly "live_session": __TablesBase["liveSession"];
  /** @deprecated Use `projectMember` instead. This alias will be removed in the next major version. */
  readonly "project_member": __TablesBase["projectMember"];
  /** @deprecated Use `projectMetadata` instead. This alias will be removed in the next major version. */
  readonly "project_metadata": __TablesBase["projectMetadata"];
  /** @deprecated Use `shareInvite` instead. This alias will be removed in the next major version. */
  readonly "share_invite": __TablesBase["shareInvite"];
};

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const tablesBase: __TablesBase = __makeQueryBuilder(tablesSchema.schemaType);
export const tables: Tables = __withTableAccessorAliases(tablesBase, true) as Tables;

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = Omit<__EventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = Omit<__ReducerEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = Omit<__SubscriptionEventContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The context type returned in callbacks for error events. */
export type ErrorContext = Omit<__ErrorContextInterface<typeof REMOTE_MODULE>, "db"> & { db: DbView };
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  declare db: DbView;

  constructor(config: __DbConnectionConfig<typeof REMOTE_MODULE>) {
    super(config);
    this.db = __withTableAccessorAliases(this.db) as DbView;
  }

  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

