// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  connectionId: __t.connectionId().primaryKey().name("connection_id"),
  projectId: __t.string().name("project_id"),
  identity: __t.identity(),
  sceneId: __t.string().name("scene_id"),
  playhead: __t.i64(),
  selection: __t.array(__t.string()),
  isPlaying: __t.bool().name("is_playing"),
  cursorX: __t.f32().name("cursor_x"),
  cursorY: __t.f32().name("cursor_y"),
  updatedAt: __t.timestamp().name("updated_at"),
});
