// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  projectId: __t.string().primaryKey().name("project_id"),
  canvasWidth: __t.u32().name("canvas_width"),
  canvasHeight: __t.u32().name("canvas_height"),
  fpsNumerator: __t.u32().name("fps_numerator"),
  fpsDenominator: __t.u32().name("fps_denominator"),
  background: __t.string(),
  extra: __t.string(),
});
