// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  SplitSide,
} from "./types";

export default {
  projectId: __t.string(),
  clipId: __t.string(),
  splitTime: __t.i64(),
  get retain() {
    return SplitSide;
  },
  rightClipId: __t.option(__t.string()),
};
