// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TrackGroup,
  TrackKind,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  projectId: __t.string().name("project_id"),
  sceneId: __t.string().name("scene_id"),
  get group() {
    return TrackGroup;
  },
  get kind() {
    return TrackKind;
  },
  name: __t.string(),
  position: __t.u32(),
  muted: __t.bool(),
  hidden: __t.bool(),
  revision: __t.u64(),
});
