// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `ActorKind`.
export const ActorKind = __t.enum("ActorKind", {
  Human: __t.unit(),
  Agent: __t.unit(),
});
export type ActorKind = __Infer<typeof ActorKind>;

export const Asset = __t.object("Asset", {
  id: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  get storage() {
    return AssetStorage;
  },
  location: __t.string(),
  mimeType: __t.string(),
  byteSize: __t.option(__t.u64()),
  width: __t.option(__t.u32()),
  height: __t.option(__t.u32()),
  duration: __t.option(__t.i64()),
  createdAt: __t.timestamp(),
});
export type Asset = __Infer<typeof Asset>;

export const AssetChunk = __t.object("AssetChunk", {
  id: __t.string(),
  projectId: __t.string(),
  assetId: __t.string(),
  chunkIndex: __t.u32(),
  chunkCount: __t.u32(),
  bytes: __t.byteArray(),
});
export type AssetChunk = __Infer<typeof AssetChunk>;

export const AssetInput = __t.object("AssetInput", {
  id: __t.string(),
  name: __t.string(),
  get storage() {
    return AssetStorage;
  },
  location: __t.string(),
  mimeType: __t.string(),
  byteSize: __t.option(__t.u64()),
  width: __t.option(__t.u32()),
  height: __t.option(__t.u32()),
  duration: __t.option(__t.i64()),
});
export type AssetInput = __Infer<typeof AssetInput>;

// The tagged union or sum type for the algebraic type `AssetStorage`.
export const AssetStorage = __t.enum("AssetStorage", {
  Local: __t.unit(),
  S3: __t.unit(),
  R2: __t.unit(),
  Spacetime: __t.unit(),
});
export type AssetStorage = __Infer<typeof AssetStorage>;

export const Clip = __t.object("Clip", {
  id: __t.string(),
  projectId: __t.string(),
  trackId: __t.string(),
  get kind() {
    return ClipKind;
  },
  name: __t.string(),
  startTime: __t.i64(),
  duration: __t.i64(),
  trimStart: __t.i64(),
  trimEnd: __t.i64(),
  sourceDuration: __t.option(__t.i64()),
  mediaId: __t.option(__t.string()),
  rate: __t.f64(),
  volumeDb: __t.f32(),
  muted: __t.bool(),
  hidden: __t.bool(),
  data: __t.string(),
  revision: __t.u64(),
  updatedAt: __t.timestamp(),
  updatedBy: __t.identity(),
  origin: __t.option(__t.connectionId()),
});
export type Clip = __Infer<typeof Clip>;

export const ClipEffect = __t.object("ClipEffect", {
  id: __t.string(),
  clipId: __t.string(),
  projectId: __t.string(),
  effectType: __t.string(),
  position: __t.u32(),
  enabled: __t.bool(),
  params: __t.string(),
  revision: __t.u64(),
});
export type ClipEffect = __Infer<typeof ClipEffect>;

export const ClipInput = __t.object("ClipInput", {
  id: __t.string(),
  trackId: __t.string(),
  get kind() {
    return ClipKind;
  },
  name: __t.string(),
  startTime: __t.i64(),
  duration: __t.i64(),
  trimStart: __t.i64(),
  trimEnd: __t.i64(),
  sourceDuration: __t.option(__t.i64()),
  mediaId: __t.option(__t.string()),
  rate: __t.f64(),
  volumeDb: __t.f32(),
  muted: __t.bool(),
  hidden: __t.bool(),
  data: __t.string(),
});
export type ClipInput = __Infer<typeof ClipInput>;

// The tagged union or sum type for the algebraic type `ClipKind`.
export const ClipKind = __t.enum("ClipKind", {
  Video: __t.unit(),
  Image: __t.unit(),
  Text: __t.unit(),
  Audio: __t.unit(),
  Sticker: __t.unit(),
  Graphic: __t.unit(),
  Effect: __t.unit(),
});
export type ClipKind = __Infer<typeof ClipKind>;

export const Collaborator = __t.object("Collaborator", {
  connectionId: __t.connectionId(),
  projectId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  color: __t.string(),
  get kind() {
    return ActorKind;
  },
  get role() {
    return MemberRole;
  },
  canWrite: __t.bool(),
  atCapacity: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Collaborator = __Infer<typeof Collaborator>;

export const EditHistory = __t.object("EditHistory", {
  id: __t.u64(),
  projectId: __t.string(),
  revision: __t.u64(),
  get op() {
    return EditOp;
  },
  targetId: __t.string(),
  actor: __t.identity(),
  get actorKind() {
    return ActorKind;
  },
  origin: __t.option(__t.connectionId()),
  summary: __t.string(),
  payload: __t.string(),
  at: __t.timestamp(),
});
export type EditHistory = __Infer<typeof EditHistory>;

// The tagged union or sum type for the algebraic type `EditOp`.
export const EditOp = __t.enum("EditOp", {
  CreateProject: __t.unit(),
  RenameProject: __t.unit(),
  SetProjectMetadata: __t.unit(),
  AddTrack: __t.unit(),
  ReorderTrack: __t.unit(),
  SetTrackMuted: __t.unit(),
  SetTrackHidden: __t.unit(),
  DeleteTrack: __t.unit(),
  AddClip: __t.unit(),
  MoveClip: __t.unit(),
  TrimClip: __t.unit(),
  SplitClip: __t.unit(),
  DeleteClip: __t.unit(),
  SetVolume: __t.unit(),
  SetClipMuted: __t.unit(),
  SetClipHidden: __t.unit(),
  UpdateClipData: __t.unit(),
  AddEffect: __t.unit(),
  RemoveEffect: __t.unit(),
  ToggleEffect: __t.unit(),
  UpdateEffectParams: __t.unit(),
  ReorderEffect: __t.unit(),
  RegisterAsset: __t.unit(),
  RemoveAsset: __t.unit(),
});
export type EditOp = __Infer<typeof EditOp>;

export const LiveSession = __t.object("LiveSession", {
  projectId: __t.string(),
  host: __t.identity(),
  active: __t.bool(),
  startedAt: __t.timestamp(),
});
export type LiveSession = __Infer<typeof LiveSession>;

// The tagged union or sum type for the algebraic type `MemberRole`.
export const MemberRole = __t.enum("MemberRole", {
  Owner: __t.unit(),
  Editor: __t.unit(),
  Agent: __t.unit(),
  Viewer: __t.unit(),
});
export type MemberRole = __Infer<typeof MemberRole>;

export const MetadataInput = __t.object("MetadataInput", {
  canvasWidth: __t.u32(),
  canvasHeight: __t.u32(),
  fpsNumerator: __t.u32(),
  fpsDenominator: __t.u32(),
  background: __t.string(),
  extra: __t.string(),
});
export type MetadataInput = __Infer<typeof MetadataInput>;

export const Presence = __t.object("Presence", {
  connectionId: __t.connectionId(),
  projectId: __t.string(),
  identity: __t.identity(),
  sceneId: __t.string(),
  playhead: __t.i64(),
  selection: __t.array(__t.string()),
  isPlaying: __t.bool(),
  cursorX: __t.f32(),
  cursorY: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Presence = __Infer<typeof Presence>;

export const Project = __t.object("Project", {
  id: __t.string(),
  name: __t.string(),
  owner: __t.identity(),
  revision: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Project = __Infer<typeof Project>;

export const ProjectMember = __t.object("ProjectMember", {
  id: __t.u64(),
  projectId: __t.string(),
  identity: __t.identity(),
  get role() {
    return MemberRole;
  },
  joinedAt: __t.timestamp(),
});
export type ProjectMember = __Infer<typeof ProjectMember>;

export const ProjectMetadata = __t.object("ProjectMetadata", {
  projectId: __t.string(),
  canvasWidth: __t.u32(),
  canvasHeight: __t.u32(),
  fpsNumerator: __t.u32(),
  fpsDenominator: __t.u32(),
  background: __t.string(),
  extra: __t.string(),
});
export type ProjectMetadata = __Infer<typeof ProjectMetadata>;

export const Scene = __t.object("Scene", {
  id: __t.string(),
  projectId: __t.string(),
  name: __t.string(),
  isMain: __t.bool(),
  position: __t.u32(),
});
export type Scene = __Infer<typeof Scene>;

export const ShareInvite = __t.object("ShareInvite", {
  token: __t.string(),
  projectId: __t.string(),
  canWrite: __t.bool(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type ShareInvite = __Infer<typeof ShareInvite>;

// The tagged union or sum type for the algebraic type `SplitSide`.
export const SplitSide = __t.enum("SplitSide", {
  Both: __t.unit(),
  Left: __t.unit(),
  Right: __t.unit(),
});
export type SplitSide = __Infer<typeof SplitSide>;

export const Track = __t.object("Track", {
  id: __t.string(),
  projectId: __t.string(),
  sceneId: __t.string(),
  get group() {
    return TrackGroup;
  },
  get kind() {
    return TrackKind;
  },
  name: __t.string(),
  position: __t.u32(),
  muted: __t.bool(),
  hidden: __t.bool(),
  revision: __t.u64(),
});
export type Track = __Infer<typeof Track>;

// The tagged union or sum type for the algebraic type `TrackGroup`.
export const TrackGroup = __t.enum("TrackGroup", {
  Overlay: __t.unit(),
  Main: __t.unit(),
  Audio: __t.unit(),
});
export type TrackGroup = __Infer<typeof TrackGroup>;

// The tagged union or sum type for the algebraic type `TrackKind`.
export const TrackKind = __t.enum("TrackKind", {
  Video: __t.unit(),
  Text: __t.unit(),
  Audio: __t.unit(),
  Graphic: __t.unit(),
  Effect: __t.unit(),
});
export type TrackKind = __Infer<typeof TrackKind>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.string(),
  get kind() {
    return ActorKind;
  },
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type User = __Infer<typeof User>;

