// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddClipReducer from "../add_clip_reducer";
import AddEffectReducer from "../add_effect_reducer";
import AddSceneReducer from "../add_scene_reducer";
import AddTrackReducer from "../add_track_reducer";
import ClearPresenceReducer from "../clear_presence_reducer";
import CreateProjectReducer from "../create_project_reducer";
import CreateShareInviteReducer from "../create_share_invite_reducer";
import DeclareAgentReducer from "../declare_agent_reducer";
import DeleteClipReducer from "../delete_clip_reducer";
import DeleteProjectReducer from "../delete_project_reducer";
import DeleteTrackReducer from "../delete_track_reducer";
import JoinProjectReducer from "../join_project_reducer";
import LeaveSessionReducer from "../leave_session_reducer";
import MoveClipReducer from "../move_clip_reducer";
import PutAssetChunkReducer from "../put_asset_chunk_reducer";
import RefreshParticipantsReducer from "../refresh_participants_reducer";
import RegisterAssetReducer from "../register_asset_reducer";
import RemoveAssetReducer from "../remove_asset_reducer";
import RemoveEffectReducer from "../remove_effect_reducer";
import RemoveParticipantReducer from "../remove_participant_reducer";
import RenameProjectReducer from "../rename_project_reducer";
import ReorderEffectReducer from "../reorder_effect_reducer";
import ReorderTrackReducer from "../reorder_track_reducer";
import SendChatMessageReducer from "../send_chat_message_reducer";
import SetClipHiddenReducer from "../set_clip_hidden_reducer";
import SetClipMutedReducer from "../set_clip_muted_reducer";
import SetParticipantAccessReducer from "../set_participant_access_reducer";
import SetPlayheadReducer from "../set_playhead_reducer";
import SetProjectMetadataReducer from "../set_project_metadata_reducer";
import SetSelectionReducer from "../set_selection_reducer";
import SetTrackHiddenReducer from "../set_track_hidden_reducer";
import SetTrackMutedReducer from "../set_track_muted_reducer";
import SetUserProfileReducer from "../set_user_profile_reducer";
import SetVolumeReducer from "../set_volume_reducer";
import SplitClipReducer from "../split_clip_reducer";
import StartLiveSessionReducer from "../start_live_session_reducer";
import StopLiveSessionReducer from "../stop_live_session_reducer";
import ToggleEffectReducer from "../toggle_effect_reducer";
import TrimClipReducer from "../trim_clip_reducer";
import UpdateClipDataReducer from "../update_clip_data_reducer";
import UpdateEffectParamsReducer from "../update_effect_params_reducer";
import UpdatePresenceReducer from "../update_presence_reducer";

export type AddClipParams = __Infer<typeof AddClipReducer>;
export type AddEffectParams = __Infer<typeof AddEffectReducer>;
export type AddSceneParams = __Infer<typeof AddSceneReducer>;
export type AddTrackParams = __Infer<typeof AddTrackReducer>;
export type ClearPresenceParams = __Infer<typeof ClearPresenceReducer>;
export type CreateProjectParams = __Infer<typeof CreateProjectReducer>;
export type CreateShareInviteParams = __Infer<typeof CreateShareInviteReducer>;
export type DeclareAgentParams = __Infer<typeof DeclareAgentReducer>;
export type DeleteClipParams = __Infer<typeof DeleteClipReducer>;
export type DeleteProjectParams = __Infer<typeof DeleteProjectReducer>;
export type DeleteTrackParams = __Infer<typeof DeleteTrackReducer>;
export type JoinProjectParams = __Infer<typeof JoinProjectReducer>;
export type LeaveSessionParams = __Infer<typeof LeaveSessionReducer>;
export type MoveClipParams = __Infer<typeof MoveClipReducer>;
export type PutAssetChunkParams = __Infer<typeof PutAssetChunkReducer>;
export type RefreshParticipantsParams = __Infer<typeof RefreshParticipantsReducer>;
export type RegisterAssetParams = __Infer<typeof RegisterAssetReducer>;
export type RemoveAssetParams = __Infer<typeof RemoveAssetReducer>;
export type RemoveEffectParams = __Infer<typeof RemoveEffectReducer>;
export type RemoveParticipantParams = __Infer<typeof RemoveParticipantReducer>;
export type RenameProjectParams = __Infer<typeof RenameProjectReducer>;
export type ReorderEffectParams = __Infer<typeof ReorderEffectReducer>;
export type ReorderTrackParams = __Infer<typeof ReorderTrackReducer>;
export type SendChatMessageParams = __Infer<typeof SendChatMessageReducer>;
export type SetClipHiddenParams = __Infer<typeof SetClipHiddenReducer>;
export type SetClipMutedParams = __Infer<typeof SetClipMutedReducer>;
export type SetParticipantAccessParams = __Infer<typeof SetParticipantAccessReducer>;
export type SetPlayheadParams = __Infer<typeof SetPlayheadReducer>;
export type SetProjectMetadataParams = __Infer<typeof SetProjectMetadataReducer>;
export type SetSelectionParams = __Infer<typeof SetSelectionReducer>;
export type SetTrackHiddenParams = __Infer<typeof SetTrackHiddenReducer>;
export type SetTrackMutedParams = __Infer<typeof SetTrackMutedReducer>;
export type SetUserProfileParams = __Infer<typeof SetUserProfileReducer>;
export type SetVolumeParams = __Infer<typeof SetVolumeReducer>;
export type SplitClipParams = __Infer<typeof SplitClipReducer>;
export type StartLiveSessionParams = __Infer<typeof StartLiveSessionReducer>;
export type StopLiveSessionParams = __Infer<typeof StopLiveSessionReducer>;
export type ToggleEffectParams = __Infer<typeof ToggleEffectReducer>;
export type TrimClipParams = __Infer<typeof TrimClipReducer>;
export type UpdateClipDataParams = __Infer<typeof UpdateClipDataReducer>;
export type UpdateEffectParamsParams = __Infer<typeof UpdateEffectParamsReducer>;
export type UpdatePresenceParams = __Infer<typeof UpdatePresenceReducer>;

